Update forms to enable presets
datajoint/pharus pull request #157
Opened 2023-03-16 18:36 UTC by jverswijver

2023-03-16 19:28 UTC, A-Baji reviewed
Could you add a test for the new preset route?

2023-03-20 20:22 UTC, guzman-raphael requested changes
@jverswijver Looks great! :handshake: 

Would you just rename the new property in the spec please? Think this matches the rest of the theme better.

2023-03-20 20:22 UTC, guzman-raphael commented on tests/init/test_dynamic_api_spec.yaml
> +                    return {'preset 1': {'b_id': 14}}
Can we update this to the following? I think it is a bit cleaner.

```suggestion
              presets: >
                def presets():
                    return {'preset 1': {'b_id': 14}}
```

2023-03-20 21:10 UTC, guzman-raphael approved these changes

2023-03-20 21:10 UTC, merged